---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dlapiduz/c0-worker-gcp

inputs:
- name: om-bosh-creds
- name: pcf-prometheus-git
- name: pcf-prometheus-manifest

params:
  prometheus_secret:
  azs:
  network_name:
  vm_password:
  nginx_ip:
  pcf_sys_domain:
  pcf_ert_domain:
  pcf_opsman_admin_username:
  pcf_opsman_admin_password:
  opsman_url:
  nats_machines:
  nats_username:
  nats_password:
  grafana_admin_password:

run:
  path: pcf-prometheus-git/tasks/deploy.sh
